name: Node Continuous Integration

on:
  push:
    branches: [ working-with-github-actions ]


jobs:
  test_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: node sample-node-code.js
      